variable "controller_custom_version" {}
variable "account_name" {}
variable "account_password" {}
variable "account_email" {}
variable "aws_account_number" {}
variable "aws_access_key" {}
variable "aws_secret_key" {}
variable "controller_ip" {}
variable "controller_username" {}
variable "controller_password" {}
variable "max_upgrade" {}
